-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 10:09:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myDb` DEFAULT CHARACTER SET utf8 ;
USE `myDb` ;

-- -----------------------------------------------------
-- Table `myDb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myDb`.`Users`;

CREATE TABLE IF NOT EXISTS `myDb`.`Users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NULL,
  PRIMARY KEY (`idUser`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myDb`.`Notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myDb`.`Notifications`;

CREATE TABLE IF NOT EXISTS `myDb`.`Notifications` (
  `idNotifications` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(100),
  `Severity` VARCHAR(100),
  `Message` MEDIUMTEXT NOT NULL,
  `Details` TEXT,
  `Timestamp` DATETIME NOT NULL,
  `IsRead` TINYINT NOT NULL,
  `Users_idUser` INT NOT NULL,
  PRIMARY KEY (`idNotifications`),
  INDEX `fk_Notifications_Users_idx` (`Users_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Notifications_Users`
    FOREIGN KEY (`Users_idUser`)
    REFERENCES `myDb`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

